### ISSUE TITLE
Lehessen több piát is bekérni sorban

### ISSUE THREAD

**Issue by ktmathe** [turospista/alkoholos#1]
Minden kérdésnél lehessen megadni, hogy mit ivott, majd ne lépjen ki a program, hanem tegye fel újra a kérdést. Ez tartson addig amíg a q (quit) gombot nem nyomja a felhasználó. 
A végén listázd ki, hogy miből mennyit ivott.

**Comment by turospista** [comment]
már összeadja a piákat és kilistázza, de csak a sört.

**Comment by turospista** [comment]
na mi a következő feladat főnök?
